export const EDGE_CASE_CLIPS = [
  {
    id: 101,
    content_type: 'text',
    content_text: 'A'.repeat(20000),
    preview: 'A'.repeat(100),
    char_count: 20000,
    line_count: 1,
    category: 'text',
    is_favorite: false,
    is_pinned: false,
    created_at: Math.floor(Date.now() / 1000),
  },
  {
    id: 102,
    content_type: 'link',
    content_text: 'https://example.com/' + 'long/'.repeat(50) + 'path',
    preview: 'https://example.com/.../path',
    char_count: 270,
    line_count: 1,
    category: 'link',
    is_favorite: true,
    is_pinned: false,
    created_at: Math.floor(Date.now() / 1000) - 100,
  },
  {
    id: 103,
    content_type: 'text',
    content_text: 'Unicode test: 안녕하세요 🌍 Z͑ͫ̓ͪ̂ͫ̽͏̴̙̤̞͉͚̯̞̠͍A̴̵̜̰͔ͫ͗͢L̠ͨͧͩ͘G̴̻͈͍͔̹̑͗̎̅͛́Ǫ̵̙̹̗͂̌̌͘',
    preview: 'Unicode test: 안녕하세요 🌍...',
    char_count: 45,
    line_count: 1,
    category: 'text',
    is_favorite: false,
    is_pinned: true,
    created_at: Math.floor(Date.now() / 1000) - 200,
  },
  {
    id: 104,
    content_type: 'code',
    content_text: 'SELECT * FROM users JOIN orders ON users.id = orders.user_id WHERE orders.total > 1000;\n-- Large SQL dump\n' + 'INSERT INTO X VALUES(Y);\n'.repeat(50),
    preview: 'SELECT * FROM users JOIN orders...',
    char_count: 1350,
    line_count: 52,
    category: 'code',
    is_favorite: false,
    is_pinned: false,
    created_at: Math.floor(Date.now() / 1000) - 300,
  },
  {
    id: 105,
    content_type: 'image',
    content_text: '',
    preview: '[Image 1920x1080]',
    char_count: 0,
    line_count: 0,
    category: 'image',
    is_favorite: false,
    is_pinned: false,
    created_at: Math.floor(Date.now() / 1000) - 400,
  }
];
